#!/usr/bin/env python3
"""Build a words.txt file from the official Korean Standard Dictionary API."""

from __future__ import annotations

import argparse
import threading
import json
import re
import sys
import time
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path


API_URL = "https://stdict.korean.go.kr/api/search.do"
HANGUL_RE = re.compile(r"^[가-힣]+$")
FIRST_HANGUL = ord("가")
LAST_HANGUL = ord("힣")


def clean_word(raw: str) -> str | None:
    word = re.sub(r"[\^_\-·\s].*$", "", raw or "").strip()
    word = re.sub(r"[^가-힣]", "", word)
    if 2 <= len(word) <= 8 and HANGUL_RE.fullmatch(word):
        return word
    return None


def request_json(params: dict[str, str | int], delay: float) -> dict:
    query = urllib.parse.urlencode(params)
    url = f"{API_URL}?{query}"
    with urllib.request.urlopen(url, timeout=30) as response:
        data = response.read().decode("utf-8")
    if delay:
        time.sleep(delay)
    if not data.strip():
        return {}
    return json.loads(data)


def parse_items(payload: dict) -> tuple[list[str], int]:
    channel = payload.get("channel", {})
    total = int(channel.get("total", 0) or 0)
    raw_items = channel.get("item", [])
    if isinstance(raw_items, dict):
        raw_items = [raw_items]
    words: list[str] = []
    for item in raw_items or []:
        raw = item.get("word") or item.get("sup_no") or ""
        word = clean_word(str(raw))
        if word:
            words.append(word)
    return words, total


def search_prefix(args: argparse.Namespace, prefix: str, start: int = 1) -> tuple[list[str], int]:
    params = {
        "key": args.key,
        "q": prefix,
        "req_type": "json",
        "advanced": "y",
        "target": 1,
        "method": "start",
        "type1": "word",
        "type2": args.type2,
        "pos": 1,
        "letter_s": 2,
        "letter_e": 8,
        "start": start,
        "num": args.num,
    }
    payload = request_json(params, args.delay)
    return parse_items(payload)


def child_prefixes(prefix: str) -> list[str]:
    return [prefix + chr(code) for code in range(FIRST_HANGUL, LAST_HANGUL + 1)]


def load_checkpoint(path: Path) -> dict:
    if not path.exists():
        return {"done": [], "words": []}
    return json.loads(path.read_text(encoding="utf-8"))


def save_checkpoint(path: Path, done: set[str], words: set[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {"done": sorted(done), "words": sorted(words)}
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def collect_prefix(
    args: argparse.Namespace,
    prefix: str,
    words: set[str],
    done: set[str],
    checkpoint: Path,
    lock: threading.Lock | None = None,
) -> None:
    if prefix in done:
        return

    page_words, total = search_prefix(args, prefix, 1)
    if args.verbose:
        print(f"{prefix}: total={total} first_page={len(page_words)}", file=sys.stderr)

    if total > args.split_threshold and len(prefix) < args.max_prefix_len:
        for child in child_prefixes(prefix):
            collect_prefix(args, child, words, done, checkpoint, lock)
        if lock:
            with lock:
                done.add(prefix)
                save_checkpoint(checkpoint, done, words)
        else:
            done.add(prefix)
            save_checkpoint(checkpoint, done, words)
        return

    if lock:
        with lock:
            words.update(page_words)
    else:
        words.update(page_words)
    start = 1 + args.num
    while start <= total and start <= args.api_start_limit:
        page_words, _ = search_prefix(args, prefix, start)
        if not page_words:
            break
        if lock:
            with lock:
                words.update(page_words)
        else:
            words.update(page_words)
        start += args.num

    if total > args.api_start_limit + args.num - 1 and args.verbose:
        print(
            f"{prefix}: stopped at API start limit {args.api_start_limit}; "
            "lower --split-threshold for exhaustive recursive collection",
            file=sys.stderr,
        )

    if lock:
        with lock:
            done.add(prefix)
            save_checkpoint(checkpoint, done, words)
    else:
        done.add(prefix)
        save_checkpoint(checkpoint, done, words)


def write_words(path: Path, words: set[str], args: argparse.Namespace) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by tools/build_official_stdict_words.py",
        "# Source: National Institute of Korean Language Standard Korean Dictionary OpenAPI",
        f"# type2={args.type2}",
        f"# count={len(words)}",
        "",
    ]
    lines.extend(sorted(words, key=lambda word: (word[0], len(word), word)))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build words.txt from stdict.korean.go.kr OpenAPI.")
    parser.add_argument("--key", required=True, help="Standard Korean Dictionary OpenAPI key.")
    parser.add_argument("--out", required=True, help="Output words.txt path.")
    parser.add_argument("--type2", default="all", help="Word origin filter. Use all or loanword.")
    parser.add_argument("--prefixes", nargs="*", help="Prefixes to collect. Defaults to 가 through 힣.")
    parser.add_argument("--resume", action="store_true", help="Resume from checkpoint next to the output file.")
    parser.add_argument("--verbose", action="store_true", help="Print progress to stderr.")
    parser.add_argument("--num", type=int, default=100, help="API page size.")
    parser.add_argument("--delay", type=float, default=0.08, help="Delay between API requests in seconds.")
    parser.add_argument("--split-threshold", type=int, default=900, help="Recursively split prefixes above this total.")
    parser.add_argument("--max-prefix-len", type=int, default=2, help="Maximum recursive prefix length.")
    parser.add_argument("--api-start-limit", type=int, default=801, help="Highest start offset to request for one prefix.")
    parser.add_argument("--workers", type=int, default=1, help="Parallel top-level prefix workers.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    out = Path(args.out)
    checkpoint = out.with_suffix(out.suffix + ".checkpoint.json")
    checkpoint_data = load_checkpoint(checkpoint) if args.resume else {"done": [], "words": []}
    done = set(checkpoint_data.get("done", []))
    words = set(checkpoint_data.get("words", []))

    prefixes = args.prefixes or [chr(code) for code in range(FIRST_HANGUL, LAST_HANGUL + 1)]
    if args.workers > 1:
        lock = threading.Lock()
        with ThreadPoolExecutor(max_workers=args.workers) as executor:
            futures = [
                executor.submit(collect_prefix, args, prefix, words, done, checkpoint, lock)
                for prefix in prefixes
            ]
            for future in as_completed(futures):
                future.result()
    else:
        for prefix in prefixes:
            collect_prefix(args, prefix, words, done, checkpoint)

    write_words(out, words, args)
    if args.verbose:
        print(f"wrote {len(words)} words to {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
