#!/usr/bin/env python3
"""Build Korean blocked-word data from words removed by the noun-only filter."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

HANGUL_RE = re.compile(r"^[가-힣]{2,}$")


def read_words(path: Path) -> set[str]:
    words: set[str] = set()
    if not path.exists():
        return words
    for line in path.read_text(encoding="utf-8").splitlines():
        word = line.strip()
        if not word or word.startswith("#"):
            continue
        if HANGUL_RE.fullmatch(word):
            words.add(word)
    return words


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create Korean blocked words from removed dictionary entries.")
    parser.add_argument("--previous", required=True, help="Previous broad Korean words file.")
    parser.add_argument("--current", default="public/words.txt", help="Current noun-only Korean words file.")
    parser.add_argument("--out", default="public/words-blocked.txt", help="Blocked words output file.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    previous = read_words(Path(args.previous))
    current = read_words(Path(args.current))
    blocked = previous - current
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    meta = [
        "# Generated by tools/build_korean_blocked_words.py",
        "# Reason: Korean game dictionary now allows noun entries only.",
        f"# Count: {len(blocked)}",
        "",
    ]
    out.write_text("\n".join(meta + sorted(blocked)) + "\n", encoding="utf-8")
    print(f"previous={len(previous)} current={len(current)} blocked={len(blocked)} wrote={out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
