param(
  [Parameter(Mandatory = $true)]
  [string]$InputDir,

  [Parameter(Mandatory = $true)]
  [string]$Out,

  [int]$MaxFiles = 0
)

$ErrorActionPreference = 'Stop'
$HangulSyllablePattern = '[\uAC00-\uD7A3]'
$WordUnit = ([char]0xB2E8).ToString() + ([char]0xC5B4).ToString()
$AllowedPosParts = @(
  (([char]0xBA85).ToString() + ([char]0xC0AC).ToString())
)
$BlockedPosParts = @(
  (([char]0xB300).ToString() + ([char]0xBA85).ToString() + ([char]0xC0AC).ToString())
)

function Clean-Word {
  param([string]$Raw)

  if ([string]::IsNullOrWhiteSpace($Raw)) {
    return $null
  }

  $word = $Raw.Trim()
  $word = [regex]::Replace($word, '[\^_\-·\s].*$', '')
  $word = [regex]::Replace($word, "[^$script:HangulSyllablePattern]", '')

  if ($word -match "^$script:HangulSyllablePattern{2,}$") {
    return $word
  }
  return $null
}

$resolvedInput = (Resolve-Path -LiteralPath $InputDir).Path
$outFull = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Out)
$outDir = Split-Path -Parent $outFull
if ($outDir -and -not (Test-Path -LiteralPath $outDir)) {
  New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

$files = Get-ChildItem -LiteralPath $resolvedInput -Filter '*.xls' -File |
  Sort-Object {
    if ($_.BaseName -match '_(\d+)$') { [int]$Matches[1] } else { [int]::MaxValue }
  }

if ($MaxFiles -gt 0) {
  $files = $files | Select-Object -First $MaxFiles
}

if (-not $files) {
  throw "No .xls files found in $resolvedInput"
}

$words = [System.Collections.Generic.HashSet[string]]::new()
$excel = New-Object -ComObject Excel.Application
$excel.Visible = $false
$excel.DisplayAlerts = $false

try {
  $fileIndex = 0
  foreach ($file in $files) {
    $fileIndex += 1
    Write-Host ("[{0}/{1}] {2}" -f $fileIndex, $files.Count, $file.Name)

    $workbook = $excel.Workbooks.Open($file.FullName, $null, $true)
    try {
      $sheet = $workbook.Worksheets.Item(1)
      $used = $sheet.UsedRange
      $values = $used.Value2
      $rows = $used.Rows.Count
      $cols = $used.Columns.Count

      if ($cols -lt 12) {
        Write-Warning "$($file.Name): expected at least 12 columns, found $cols"
        continue
      }

      for ($row = 2; $row -le $rows; $row += 1) {
        $rawWord = [string]$values[$row, 1]
        $unit = [string]$values[$row, 2]
        $pos = [string]$values[$row, 12]

        if ($unit -ne $WordUnit) {
          continue
        }
        $allowedPos = $false
        foreach ($posPart in $AllowedPosParts) {
          if ($pos.Contains($posPart)) {
            $allowedPos = $true
            break
          }
        }
        foreach ($posPart in $BlockedPosParts) {
          if ($pos.Contains($posPart)) {
            $allowedPos = $false
            break
          }
        }
        if (-not $allowedPos) {
          continue
        }

        $word = Clean-Word $rawWord
        if ($word) {
          [void]$words.Add($word)
        }
      }
    }
    finally {
      $workbook.Close($false)
      [void][System.Runtime.InteropServices.Marshal]::ReleaseComObject($workbook)
    }
  }
}
finally {
  $excel.Quit()
  [void][System.Runtime.InteropServices.Marshal]::ReleaseComObject($excel)
  [GC]::Collect()
  [GC]::WaitForPendingFinalizers()
}

$sortedWords = @($words) | Sort-Object
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Generated by tools/build_words_from_stdict_xls.ps1')
$lines.Add('# Source: National Institute of Korean Language Standard Korean Dictionary full XLS download')
$lines.Add("# InputDir: $resolvedInput")
$lines.Add("# Files: $($files.Count)")
$lines.Add('# Filters: lexical unit=word, noun entries only, /^[Hangul syllables]{2,}$/')
$lines.Add("# Count: $($sortedWords.Count)")
$lines.Add('')
foreach ($word in $sortedWords) {
  $lines.Add($word)
}

$encoding = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllLines($outFull, $lines, $encoding)
Write-Host "Wrote $($sortedWords.Count) words to $outFull"
