#!/usr/bin/env python3
"""Merge Korean words from Kaikki/Wiktextract JSONL into words.txt."""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path


DEFAULT_URL = "https://kaikki.org/dictionary/Korean/kaikki.org-dictionary-Korean.jsonl"
HANGUL_RE = re.compile(r"^[가-힣]{2,}$")
SEPARATOR_RE = re.compile(r"[\s\-\^·ㆍ]+")
ALLOWED_POS = {"noun", "proper-name", "name"}


def clean_word(raw: object) -> str | None:
    if not isinstance(raw, str):
        return None
    compact = SEPARATOR_RE.sub("", raw.strip())
    compact = re.sub(r"[^가-힣]", "", compact)
    if HANGUL_RE.fullmatch(compact):
        return compact
    return None


def read_existing(path: Path) -> tuple[list[str], set[str]]:
    meta: list[str] = []
    words: set[str] = set()
    if not path.exists():
        return meta, words
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            meta.append(stripped)
            continue
        word = clean_word(stripped)
        if word:
            words.add(word)
    return meta, words


def iter_lines(source: str):
    if source.startswith("http://") or source.startswith("https://"):
        with urllib.request.urlopen(source, timeout=60) as response:
            for raw in response:
                yield raw.decode("utf-8", "replace")
    else:
        with open(source, "r", encoding="utf-8") as handle:
            yield from handle


def extract_words(source: str, include_forms: bool, verbose: bool) -> set[str]:
    words: set[str] = set()
    seen = 0
    for line in iter_lines(source):
        seen += 1
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue

        pos = str(entry.get("pos") or "").lower()
        if pos not in ALLOWED_POS:
            continue

        word = clean_word(entry.get("word"))
        if word:
            words.add(word)

        if include_forms:
            for form in entry.get("forms") or []:
                form_word = clean_word(form.get("form") if isinstance(form, dict) else None)
                if form_word:
                    words.add(form_word)

        if verbose and seen % 20000 == 0:
            print(f"read {seen:,} lines; extracted {len(words):,} words", file=sys.stderr)
    return words


def write_words(path: Path, words: set[str], source: str, previous_meta: list[str]) -> None:
    merged_meta = [
        "# Generated by merging local dictionary sources",
        "# Base: National Institute of Korean Language Standard Korean Dictionary full XLS download",
        f"# Supplement: Kaikki/Wiktextract Korean JSONL ({source})",
        "# Filters: noun/proper-name/name, /^[Hangul syllables]{2,}$/",
        f"# Count: {len(words)}",
        "",
    ]
    if previous_meta:
        merged_meta.append("# Previous metadata:")
        merged_meta.extend(f"#   {line.lstrip('# ').strip()}" for line in previous_meta[:12])
        merged_meta.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(merged_meta + sorted(words)) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Merge Kaikki Korean words into words.txt.")
    parser.add_argument("--words", default="public/words.txt", help="Existing words.txt to update.")
    parser.add_argument("--source", default=DEFAULT_URL, help="Kaikki JSONL URL or local file.")
    parser.add_argument("--include-forms", action="store_true", help="Also include form entries.")
    parser.add_argument("--verbose", action="store_true", help="Print progress.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    path = Path(args.words)
    previous_meta, current_words = read_existing(path)
    supplement_words = extract_words(args.source, args.include_forms, args.verbose)
    before = len(current_words)
    current_words.update(supplement_words)
    write_words(path, current_words, args.source, previous_meta)
    print(f"existing={before} supplement={len(supplement_words)} merged={len(current_words)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
