#!/usr/bin/env python3
"""Merge Korean words from the Urimalsaem full XML download into words.txt."""

from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


HANGUL_RE = re.compile(r"^[가-힣]{2,}$")
SEPARATOR_RE = re.compile(r"[\s\-\^·ㆍㆍ]+")
BLOCKED_POS = {"감탄사 없음", "어미", "접사", "조사", "품사 없음"}
BLOCKED_TYPES = {"옛말"}


def clean_word(raw: object) -> str | None:
    if not isinstance(raw, str):
        return None
    compact = SEPARATOR_RE.sub("", raw.strip())
    compact = re.sub(r"[^가-힣]", "", compact)
    if HANGUL_RE.fullmatch(compact):
        return compact
    return None


def child_text(element: ET.Element, path: str) -> str:
    found = element.find(path)
    return "".join(found.itertext()).strip() if found is not None else ""


def read_existing(path: Path) -> tuple[list[str], set[str]]:
    meta: list[str] = []
    words: set[str] = set()
    if not path.exists():
        return meta, words
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            meta.append(stripped)
            continue
        word = clean_word(stripped)
        if word:
            words.add(word)
    return meta, words


def item_allowed(item: ET.Element) -> bool:
    sense_infos = item.findall("senseInfo")
    if not sense_infos:
        return False

    for sense in sense_infos:
        pos = child_text(sense, "pos")
        kind = child_text(sense, "type")
        if pos in BLOCKED_POS or kind in BLOCKED_TYPES:
            continue
        if pos == "명사" or pos.endswith(" 명사"):
            return True
    return False


def blocked_words_from_item(item: ET.Element) -> set[str]:
    out: set[str] = set()
    word = clean_word(child_text(item, "wordInfo/word"))
    if word and not item_allowed(item):
        out.add(word)
    for conjugation in item.findall(".//conjugation"):
        form = clean_word("".join(conjugation.itertext()).strip())
        if form:
            out.add(form)
    return out


def extract_blocked_words(input_dir: Path, verbose: bool) -> set[str]:
    words: set[str] = set()
    files = sorted(input_dir.glob("*.xml"))
    for file_index, path in enumerate(files, 1):
        before = len(words)
        items = 0
        for event, elem in ET.iterparse(path, events=("end",)):
            if elem.tag == "item":
                items += 1
                words.update(blocked_words_from_item(elem))
                elem.clear()
        if verbose:
            added = len(words) - before
            print(f"{file_index}/{len(files)} {path.name}: blocked-items={items:,} added={added:,} total={len(words):,}", file=sys.stderr)
    return words


def words_from_item(item: ET.Element, include_conjugations: bool) -> set[str]:
    out: set[str] = set()
    if not item_allowed(item):
        return out

    word = clean_word(child_text(item, "wordInfo/word"))
    if word:
        out.add(word)

    if include_conjugations:
        for conjugation in item.findall(".//conjugation"):
            form = clean_word("".join(conjugation.itertext()).strip())
            if form:
                out.add(form)
    return out


def extract_words(input_dir: Path, include_conjugations: bool, verbose: bool) -> set[str]:
    words: set[str] = set()
    files = sorted(input_dir.glob("*.xml"))
    for file_index, path in enumerate(files, 1):
        before = len(words)
        items = 0
        for event, elem in ET.iterparse(path, events=("end",)):
            if elem.tag == "item":
                items += 1
                words.update(words_from_item(elem, include_conjugations))
                elem.clear()
        if verbose:
            added = len(words) - before
            print(f"{file_index}/{len(files)} {path.name}: items={items:,} added={added:,} total={len(words):,}", file=sys.stderr)
    return words


def write_words(path: Path, words: set[str], input_dir: Path, previous_meta: list[str]) -> None:
    meta = [
        "# Generated by merging local dictionary sources",
        "# Base: NIKL Standard Korean Dictionary full XLS download + Kaikki/Wiktionary Korean",
        f"# Supplement: Urimalsaem full XML download ({input_dir})",
        "# Filters: pure Hangul syllables, length >= 2, noun entries only",
        f"# Count: {len(words)}",
        "",
    ]
    if previous_meta:
        meta.append("# Previous metadata:")
        meta.extend(f"#   {line.lstrip('# ').strip()}" for line in previous_meta[:12])
        meta.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(meta + sorted(words)) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Merge Urimalsaem XML words into public/words.txt.")
    parser.add_argument("--words", default="public/words.txt", help="Existing words.txt to update.")
    parser.add_argument("--input-dir", default="전체 내려받기_우리말샘_xml_20260602", help="Urimalsaem XML directory.")
    parser.add_argument("--include-conjugations", action="store_true", help="Include conjugation forms.")
    parser.add_argument("--verbose", action="store_true", help="Print progress.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    words_path = Path(args.words)
    input_dir = Path(args.input_dir)
    previous_meta, current_words = read_existing(words_path)
    supplement_words = extract_words(input_dir, args.include_conjugations, args.verbose)
    before = len(current_words)
    current_words.update(supplement_words)
    write_words(words_path, current_words, input_dir, previous_meta)
    print(f"existing={before} supplement={len(supplement_words)} merged={len(current_words)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
